services:
  portfolio:
    build: .
    container_name: portfolio
    networks:
      - jasper
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  jasper:
    external: true